### PR TITLE
Feat: Flutter version 3.22.2

### LINKED ISSUE #27: Incompatible with flutter 3.22.2
When I compile for android I get these errors:
```
../../../.pub-cache/hosted/pub.dev/combine-0.5.7-0.1.pre/lib/src/bindings/isolate_bindings/isolate_binding.dart:13:7: Error: The non-abstract class 'IsolateBinding' is missing implementations for these members:
 - SchedulerBinding.resetInternalState
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class IsolateBinding extends BindingBase
      ^^^^^^^^^^^^^^
../../../Android/flutter/packages/flutter/lib/src/scheduler/binding.dart:397:8: Context: 'SchedulerBinding.resetInternalState' is defined here.
  void resetInternalState() {
       ^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

environment:
```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

### PR DESCRIPTION
**Pull request by purofle**
fix: #27 

# PR Checklist

- [ ] Code is 100% covered. 
- [ ] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [ ] Changelog is updated.

### CODE REVIEW

**Comment by Maksimka101** [comment]
Thanks. I'll check it out later when I'll get to computer

**Comment by purofle** [comment]
> Thanks. I'll check it out later when I'll get to computer

Is this useful?

**Comment by mdejeans** [comment]
Up please ! :)

**Comment by Maksimka101** [comment]
New version is published!🙂

**Pull request merged**
